# Generated by Django 5.2.2 on 2025-06-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('land', 'Terrain'), ('house_sale', 'Maison (Vente)'), ('house_rent', 'Maison (Location)')], max_length=20),
        ),
    ]
